### ISSUE TITLE
ToDo - Tarefa 3

### ISSUE THREAD

**Issue by bambokianr** [bambokianr/pacman-threejs#13]
- [ ] Lógica de pontuação
- [ ] Função `updateGamePerspectiveCamera` - definir rotação da câmera de acordo com a direção do pacman
- [ ] Sons?
- [x] Bug com função `reloadGame()` - impressão que os fantasmas tão mais acelerados rs / fica recarregando sempre como se o pacman estivesse sendo atacado pelo fantasma mas não tá
- [ ] Instruções do jogo?
