### ISSUE TITLE
ToDo - Tarefa 1

### ISSUE THREAD

**Issue by bambokianr** [bambokianr/pacman-threejs#6]
- [x] Construção do labirinto
- [x] Desenho do pacman em cena
- [x] Pacman animado - movimento da boca (angulação)
- [x] Desenho do fantasma em cena
- [x] Fantasma animado - movimento na vertical ('flutuando')
- [x] Criar uma estrutura para salvar o `skeleton` de vários fantasmas  (movimentos e cores independentes)
- [x] Desenho das 'comidas' em tela - diferenciar os dois tipos
- [x] Implementar câmera perspectiva
- [x] Implementar câmera na visão do pacman
- [x] Alternar entre as duas câmeras
- [ ] Usar CDN dos módulos Three.js preferencialmente (https://cdnjs.com/)
