### ISSUE TITLE
ToDo - Tarefa 2

### ISSUE THREAD

**Issue by bambokianr** [bambokianr/pacman-threejs#8]
- [x] Importar modelo pronto em 3D
- [x] Mapeamento de textura em algum objeto - moedas?
- [x] Implementar shader em GLSL
- [x] Melhorar sombreamentos e lights (também com MaterialShader)
